web:
  build: .
  restart: always
  command: python manage.py runserver 0.0.0.0:8000
#  volumes:
#    - .:/app/src
  ports:
    - "8000:8000"
  links:
    - redis
    - mysql
 
redis:
  image: redis:latest
  volumes:
    - /var/lib/redis
  ports:
    - "6379"
 
mysql:
  image: mysql:latest
  volumes:
    - /var/lib/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: dbmskids 
